In [2]:
#single dimentional array
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [8]:
#multi dimentional array
import numpy as np
n2=np.array([[1,2,3,4,5],[9,5,6,7,0]])
n2

array([[1, 2, 3, 4, 5],
       [9, 5, 6, 7, 0]])

In [10]:
type(n2)

numpy.ndarray

In [11]:
#initializing numpy with zeros
import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [12]:
import numpy as np
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
import numpy as np
n1=np.zeros((3,3))
n1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
n1=np.zeros((10,10))
n1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
n1=np.zeros((0,0))
n1

array([], shape=(0, 0), dtype=float64)

In [17]:
import numpy as np
n1=np.full((2,2),5)
n1


array([[5, 5],
       [5, 5]])

In [20]:
import numpy as nop
n1=np.arange(1,10)
n1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
import numpy as np
n1=np.arange(10,51)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [23]:
import numpy as np
n1=np.arange(10,101,10)
n1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [30]:
n1=np.random.randint(10,50,6)
n1

array([23, 30, 14, 36, 43, 39])

In [31]:
import numpy as np
n1=np.array(["bts","bp"])
n1

array(['bts', 'bp'], dtype='<U3')

In [49]:
n1=np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)

In [53]:
import numpy as np
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [58]:
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [59]:
type(s1)

pandas.core.series.Series

In [60]:
s1=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [61]:
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64